# SPDX-License-Identifier: Apache-2.0
"""Tiny synthetic Granite base checkpoints, and the shapes derived from a config.

The dims are what an adapter's tensors have to match, read off any base config
(real or synthetic); the tiny writer gives the CPU tests a loadable base with no
download. Adapters themselves are generated by
:mod:`tests.shared.synthetic_adapters`.

Two MLP spellings are supported, matching the composer's two arch descriptors:

* ``"shared"`` — ``shared_mlp.input_linear`` (fused gate|up) and
  ``shared_mlp.output_linear``, used by ``granitemoehybrid`` bases.
* ``"dense"`` — ``mlp.gate_proj`` / ``mlp.up_proj`` / ``mlp.down_proj``, used by
  ``granite`` dense bases (granite-4.1-3b among them).
"""

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

import torch
from safetensors.torch import save_file


@dataclass(frozen=True)
class BaseDims:
    """The base-model shapes a PEFT adapter's tensors have to match."""

    hidden: int
    intermediate: int
    q_width: int
    kv_width: int
    num_layers: int
    mlp_style: str  # "shared" | "dense"

    def __post_init__(self):
        if self.mlp_style not in ("shared", "dense"):
            raise ValueError(
                f"mlp_style must be 'shared' or 'dense', got {self.mlp_style!r}"
            )


def dims_from_config(config) -> BaseDims:
    """Derive :class:`BaseDims` from a HuggingFace base config."""
    hidden = config.hidden_size
    num_heads = config.num_attention_heads
    head_dim = getattr(config, "head_dim", None) or hidden // num_heads
    kv_heads = config.num_key_value_heads
    model_type = getattr(config, "model_type", "")
    shared_mlp = model_type == "granitemoehybrid"
    # granitemoehybrid's shared MLP is sized by shared_intermediate_size;
    # intermediate_size sizes the routed experts, which a shared_mlp adapter
    # never touches.
    intermediate = (
        getattr(config, "shared_intermediate_size", None) if shared_mlp else None
    )
    if intermediate is None:
        intermediate = config.intermediate_size
    return BaseDims(
        hidden=hidden,
        intermediate=intermediate,
        q_width=num_heads * head_dim,
        kv_width=kv_heads * head_dim,
        num_layers=config.num_hidden_layers,
        mlp_style="shared" if shared_mlp else "dense",
    )


def _randn(key: str, seed: int, *shape: int, scale: float) -> torch.Tensor:
    """Reproducible ``N(0, scale)`` tensor keyed by ``(seed, key)``.

    ``hashlib`` rather than ``hash()``: str hashing is salted per process, so the
    same base would otherwise differ between runs.
    """
    digest = hashlib.blake2b(f"{seed}:{key}".encode(), digest_size=8).digest()
    gen = torch.Generator().manual_seed(int.from_bytes(digest, "big") % (2**63))
    return torch.randn(*shape, generator=gen) * scale


def write_tiny_granite_base(
    path: Path,
    *,
    mlp_style: str = "dense",
    hidden: int = 64,
    intermediate: int = 128,
    num_layers: int = 2,
    num_heads: int = 4,
    num_kv_heads: int = 4,
    head_dim: int = 16,
    vocab_size: int = 300,
    seed: int = 0,
) -> Path:
    """Write a tiny random Granite base checkpoint for CPU compose tests.

    ``mlp_style="dense"`` emits a ``granite`` base (``mlp.gate/up/down_proj``);
    ``"shared"`` emits an all-attention dense ``granitemoehybrid`` base
    (``shared_mlp.input_linear`` / ``output_linear``, ``num_local_experts=0``),
    which is the arch the real granite-4.x checkpoints use.
    """
    path.mkdir(parents=True, exist_ok=True)
    shared = mlp_style == "shared"
    config = {
        "model_type": "granitemoehybrid" if shared else "granite",
        "architectures": [
            "GraniteMoeHybridForCausalLM" if shared else "GraniteForCausalLM"
        ],
        "vocab_size": vocab_size,
        "hidden_size": hidden,
        "intermediate_size": intermediate,
        "num_hidden_layers": num_layers,
        "num_attention_heads": num_heads,
        "num_key_value_heads": num_kv_heads,
        "head_dim": head_dim,
        "max_position_embeddings": 128,
        "rms_norm_eps": 1e-5,
        "attention_multiplier": 1.0,
        "logits_scaling": 1.0,
        "residual_multiplier": 1.0,
        "embedding_multiplier": 1.0,
        "torch_dtype": "float32",
    }
    if shared:
        config |= {
            "num_local_experts": 0,
            "num_experts_per_tok": 0,
            "shared_intermediate_size": intermediate,
            "layer_types": ["attention"] * num_layers,
            "position_embedding_type": "rope",
        }
    (path / "config.json").write_text(json.dumps(config))

    q_width, kv_width = num_heads * head_dim, num_kv_heads * head_dim
    sd = {
        "model.embed_tokens.weight": _randn(
            "embed", seed, vocab_size, hidden, scale=1.0
        )
    }
    for layer in range(num_layers):
        p = f"model.layers.{layer}"
        for mod, shape in (
            ("q_proj", (q_width, hidden)),
            ("k_proj", (kv_width, hidden)),
            ("v_proj", (kv_width, hidden)),
            ("o_proj", (hidden, q_width)),
        ):
            sd[f"{p}.self_attn.{mod}.weight"] = _randn(
                f"{p}.{mod}", seed, *shape, scale=1.0
            )
        if shared:
            sd[f"{p}.shared_mlp.input_linear.weight"] = _randn(
                f"{p}.in", seed, 2 * intermediate, hidden, scale=1.0
            )
            sd[f"{p}.shared_mlp.output_linear.weight"] = _randn(
                f"{p}.out", seed, hidden, intermediate, scale=1.0
            )
        else:
            sd[f"{p}.mlp.gate_proj.weight"] = _randn(
                f"{p}.gate", seed, intermediate, hidden, scale=1.0
            )
            sd[f"{p}.mlp.up_proj.weight"] = _randn(
                f"{p}.up", seed, intermediate, hidden, scale=1.0
            )
            sd[f"{p}.mlp.down_proj.weight"] = _randn(
                f"{p}.down", seed, hidden, intermediate, scale=1.0
            )
        sd[f"{p}.input_layernorm.weight"] = torch.ones(hidden)
        sd[f"{p}.post_attention_layernorm.weight"] = torch.ones(hidden)
    sd["model.norm.weight"] = torch.ones(hidden)
    sd["lm_head.weight"] = _randn("lm_head", seed, vocab_size, hidden, scale=1.0)

    save_file(sd, str(path / "model.safetensors"))
    return path


__all__ = [
    "BaseDims",
    "dims_from_config",
    "write_tiny_granite_base",
]
